### ISSUE TITLE
Overriding input_libretro_device for a core is being ignored

### ISSUE THREAD

**Issue by cyberluke** [fabricecaruso/batocera-ports#29]
Path: batocera-ports\emulatorLauncher\Generators\LibRetro.Generator.cs

```
if (Controllers.Count > 2 && (core == "snes9x_next" || core == "snes9x"))
                retroarchConfig["input_libretro_device_p2"] = "257";
```

In this manner, I have currently added a hardcoded fix for ZX Spectrum (Fuse):

next lines as follows:
```
            retroarchConfig["input_libretro_device_p1"] = "513";
            retroarchConfig["input_libretro_device_p3"] = "259";
```

First one is Kempton Joystick interface (p1), second is Sinclair Keyboard (p3).

After loading RetroArch, it gets set properly:
```
[libretro INFO] port 0 device 00000101
[libretro INFO] port 1 device 00000201
[libretro INFO] port 2 device 00000103
```

But core load will override and this is printed in the log after:
```
[libretro INFO] port 0 device 00000001
[libretro INFO] port 1 device 00000001
[libretro INFO] port 2 device 00000001
```

The only way to make it work is Controls -> Manage Remap Files -> Save Core Map Override --> this creates fuse.rmp in RetroArch Config folder.

How to make it automatic? I suspect the above line for Snes9x would have same issue. This is a specific device code type for a particular emulator core and is valid only for that emulator. Therefore I guess after that core loads, it will load default value (RetroPad) and ignore original values. Only Core Remap file will load it properly.

[log.txt](https://github.com/fabricecaruso/batocera-ports/files/9743061/log.txt)

**Comment by cyberluke** [comment]
I would like to provide some form of pull request to enable functionality for Retrobat. I'm currently beta testing Retrobat 5.

The following is working for me and two button joystick is finally working with Retrobat / EmuStation retroarch.cfg template generation:
\batocera-ports\emulatorLauncher\Generators\Libretro.Controllers.cs

```
            if (system == "zxspectrum" || system == "amstradcpc" || system == "amiga500" || system == "amiga1200")
            {
                foreach (var specialkey in retroarchspecials)
                {
                    retroconfig.DisableAll("input_" + specialkey.Value);
                    config["input_" + specialkey.Value] = "nul";
                }

#if DEBUG
                config["input_exit_emulator"] = "tilde";
#else
                config["input_exit_emulator"] = "escape";
#endif            
                config["input_menu_toggle"] = "f1";
                config["input_rewind"] = "f12";

                if (system == "zxspectrum")
                {
                    retroarchbtns[InputKey.a] = "a";
                    retroarchbtns[InputKey.b] = "r";
                    config["input_libretro_device_p1"] = "513";
                    config["input_libretro_device_p2"] = "0";
                    config["input_libretro_device_p3"] = "259";
                }
            }
```

 retroarchbtns[InputKey.a] = "a"; is set to fix line 228:
```
                    { InputKey.b, "a" },
                    { InputKey.a, "b" }, // A et B inversés par rapport à batocera
```

and retroarchbtns[InputKey.b] = "r"; will cause to map joystick button 2 to Space key in ZX Spectrum as ZX Spectrum have only 1 button joystick. This enables to play games such as Xenon.

**Comment by cyberluke** [comment]
BTW: the hotkeys are still annoying, cannot set them to "nul" or remove them - they are still being set, don't know why

**Comment by cyberluke** [comment]
Even I try to change the order of WriteHotKeys, so WriteControllerConfig can override that, per system, in the example above:

```
            WriteHotKeyConfig(retroconfig);

            foreach (var controller in Program.Controllers)
                WriteControllerConfig(retroconfig, controller, system);

            return true;
```

**Comment by fabricecaruso** [comment]
I'm not going to discuss things if I can't see/compare your full changes in a working branch.
There's no way to understand precisely the work you did & where you did it. I'm sure the code you sent is missing conditions...

Please commit your changes in a fork of yours so I can see & compare the whole thing.
The projet you have to fork is this one : https://github.com/fabricecaruso/batocera-ports

Also, you can write in a remap file using the property InputRemap in libretro.coreoptions.
libretro.coreoptions is probably a better place to do what you want to do.
The old code ( like if (Controllers.Count > 2 && (core == "snes9x_next" || core == "snes9x")) ) should be moved in that file too ( when I have the time )...

**Comment by cyberluke** [comment]
https://github.com/fabricecaruso/batocera-ports/pull/30

**Comment by cyberluke** [comment]
Hello Fabrice, I have added pull request. I started to use Kayl's Retrobat repository as he seems to be more updated and I wanted to primarily help with Retrobat betatesting. This pull request is only for you to easily compare the changes. It will be reworked.

Yes, InputRemap seems that it could be the solution. Thanks. It is not being used anywhere and regular core options I discovered would not work. It needs to have a remap. So I might to rework it now and I might fix your snes9x condition as well - I'm 90% sure it won't work now as well.

**Comment by fabricecaruso** [comment]
mmm you are doing it for every core & systems !?!?!?

**Comment by cyberluke** [comment]
YES FOR NOW I TOLD YOU THIS IS ON TWO PLACES NOW TO DEBUG THE CODE AND EVEN SO IT IS NOT WORKING

**Comment by cyberluke** [comment]
I know what I'm doing, now can you please stop asking hundreds of questions and either help or not help? Thank you. You see it is on two places and I'm reporting a bug and this is one of the use cases. There is previous commit setting this per system.

**Comment by cyberluke** [comment]
Per system implementation is here, did you see it ?!?!?!?!?!?
https://github.com/fabricecaruso/batocera-ports/pull/30/commits/7d008bfdab5029bc8330873a23e0e9d04183d717

It's not working, so I told you I put that line directly under snes9x to test and verify the behavior.

Also previous comment before your comment was: "This pull request is only for you to easily compare the changes. It will be reworked."

I don't know why is it so difficult to communicate with you.

**Comment by fabricecaruso** [comment]
"now can you please stop asking hundreds of questions and either help or not help?"
Seriously ?????? You are kidding I hope... 

"Also your style of communication could be better" ( ES issue )
"I don't know why is it so difficult to communicate with you"
Watch yours... Read the complete list of messages you posted in the issue again...
4 initial messages. The point of what you want to do being barely understable, what's why I asked to see the whole code. 
Reading code is far more clear than words.

I didn't ask any question, "  you are doing it for every core & systems !?!?!? " it was a remark, because you are doing it (Overriding input_libretro_device, which is the title of the issue ) for every core & systems.

Check those 2 lines. It's here : https://github.com/fabricecaruso/batocera-ports/pull/30/files#diff-3044d0ba90b09e5788e9c29aeedb56269238e1d1c1f1cb6d694ec581ee259ee6R279
I though there was a condition for them. There are no conditions. 
So : Yes, you set "input_libretro_device_p1" to 513 for every system/core.... 

_"previous comment [...] it will be reworked."._
So... You hope that I'll be able to guess what code is temporary or not ???

It's not serious... Am I really the one with a communication problem.

So what are you trying to do ?
set input_libretro_device_p1 to 513 and input_libretro_device_p3 to 259 but using a Remap.

I told you : The best solution is to write this in Libretro.CoreOptions.cs using InputRemap. 

So create a method for fuse core : ConfigureFuse, and filter to fuse code using if (core != "fuse") return;
Then :
            InputRemap["input_libretro_device_p1" = "513";
            InputRemap["input_remap_port_p1"] = "0";
            InputRemap["input_libretro_device_p3" = "259";
            InputRemap["input_remap_port_p3"] = "2"; // I assume it's 2

I did not understand your hotkey problem, neigher why so many systems are concerned ( system == "zxspectrum" || system == "amstradcpc" || system == "amiga500" || system == "amiga1200" )

**Comment by cyberluke** [comment]
I have tested all configurations on my part and this works for me: https://github.com/fabricecaruso/batocera-ports/pull/30

**Comment by cyberluke** [comment]
InputRemap["input_remap_port_p3"] = "2"; // I assume it's 2  ==> no this is really 3, it is documented in ZX Spectrum (Fuse core) documentation in Retroarch. It is very specific feature to automatically map native keyboard to emulator keyboard.

**Comment by cyberluke** [comment]
All of these systems do have native keyboard:  ( system == "zxspectrum" || system == "amstradcpc" || system == "amiga500" || system == "amiga1200" )

So if you want to play text adventure or anything, where you need to type commands, then playing only on gamepad is not enough.

**Comment by fabricecaruso** [comment]
After looking at you full PR, I have 3 questions :
- Any reason why you inverted InputKey.a & b for retroarchbtns ?  `{ InputKey.b, "a" }, { InputKey.a, "b" },`  It's going to affect every emulator/core, and this is not wanted.
- You did not explain the hasHotKey() thing. You are using this to detect if player1 controller is the keyboard ?
- You still don't use Remaps ? You said it was working only using remap files ?

**Comment by cyberluke** [comment]
I apologize, I'm bit sick this week. I just commit what I had tested and was working for me.

1) I don't know why you put this hack with A and B button because I have exact opposite issue. It is reverted for me in all emulators. So let me ask a question: What kind of joystick are you using? I'm using a classic two button PC IBM compatible joystick and button 1 and 2 are clearly numbered. Are you using some DIY arcade joystick or X-Box controller?

2) hasHotKey() is a solution for 2 button IBM PC compatible joystick and all other 2 button game controllers that do not have any extra button for hot key. We discussed on Discord that this caused issues as rewind and other actions are mapped as hotkey+button 1 or hotkey+button 2. If hotkey is undefined, then these will get triggered as a phantom action.

3) I'm sorry, I did not have time to rework is as a remap. I have found bug in another component and currently I am fixing something else in Batocera.

My testing setup:
1) Intel Core Quad, AMD Radeon R9 280x (Calamity CRT EmuDriver), Retrobat5, custom Switchres.ini with fixed modelines for Sony PVM 20''

2) Windows Media Center edition (Acer iDEA 510) with direct RCA component TV out, Geforce Go 7600, Batocera Linux and Windows 7 MCE. The GPU driver is older, so 'gl' in Retroarch will crash, but 'gl1' or 'd3d9_hlsl' works.

With Sony PVM, I have BNC audio video switch, so it has real XBox 1, PS2, PS4 connected to compare speed and visual results between emulator and real console.

With Retrobat5 I have tested:
a) PS4 controller via USB cable (force feedback vibration works only via cable)
b) original PS2 controller with USB adapter that supports force feedback and is certified for Windows 98. This one does not have vibration because it uses DirectInput and this year I fixed a bug in SlimDX library with forcefeedback (5 years old bug). Here we use SharpDX, so it will have this DirectInput FFB error and nobody fixed that ever. Mostly old flight sims had DX FFB API. Nowadays Retroarch supports only XInput FFB (X360 FFB style), so original PS2 dualshock with vibration would work if someone would fix SharpDX library and created a callback for receiving FFB.
3) a various IBM compatible joysticks (2 button, 4 button) via USB to gameport adapter (has various settings via slider)
4) various USB joysticks and gamepads

The battle I have here, it is just a part of a bigger scale war for me. I have tested the setup above and I identified around 5 components in various EmulationStation+Retroarch clones (be it Batocera, Retrobat or something else). And you see it is very time consuming and very difficult to help someone else or clarify a PR. There is also a lot of forks in these modules (for example Retroarch + Switchres 2.0 fork).

So at this moment I would be interested what everyone is testing on because I get always different results and with 5 buggy components and code changes currently, it might be a better to roll out a custom solution for Sony PVM with IBM PC joystick and IBM PC keyboard for people who are interested in emulators such as ZX Spectrum, Amstrad CPC, Amiga. What I often see is that someone tests only Nintendo and PSX, and perhaps DosBox. Done! And he even don't have a real analog CRT TV or he has this arcade CRT that is different than Sony PVM (all regular TV require NTSC and PAL by the spec and arcade_15 in switchres does not do it)

**Comment by cyberluke** [comment]
BTW 3) Yes, I guess I have core remap file now for ZX Spectrum. Yes this is fuse.rmp

```
input_libretro_device_p1 = "513"
input_libretro_device_p2 = "1"
input_libretro_device_p3 = "259"
input_libretro_device_p4 = "1"
input_libretro_device_p5 = "1"
input_player1_analog_dpad_mode = "0"
input_player2_analog_dpad_mode = "0"
input_player3_analog_dpad_mode = "0"
input_player4_analog_dpad_mode = "0"
input_player5_analog_dpad_mode = "0"
input_remap_port_p1 = "0"
input_remap_port_p2 = "1"
input_remap_port_p3 = "2"
input_remap_port_p4 = "3"
input_remap_port_p5 = "4"
```

**Comment by fabricecaruso** [comment]
1 / It's not about the controller I use. 
Windows version of EmulationStation kept the original Retropie convention where A & B are inverted on Windows compared to Linux.
That's why the controller assistant shows the button positions -> A & B names are a always bad convension are they depend on the controller you use ( nes/xbox conventions are inverted ). Instead, trust button positions ( north/east... )
So I won't accept this inversion as it will affect every core/system and, by consequence, invert buttons for every current users.
Please revert this change, or make it specific to some systems or cores only.

2/ We discussed on Discord" : We never had a conversation on Discord... 
I found a conversation in Retrobat channels, where you ask about this to Kaylh, and it's not really clear. Anyway, I'm not Kaylh. 
Well : I understand what you want to do, and it can be interesting.
But with in current PR code, if there's no hotkey with p1 controller, there's no handling at all for retroarch commands (rewind/menu_toggle...) except with zxspectrum/amstradcpc/amiga systems as you set input_rewind & input_menu_toggle with a condition for these systems. Then, there's no solution at all for the other cores/systems.
It's not acceptable in the current state as it will leave every other core/systems without a solution.

3/ You can't have a core remap file with your current PR code, unless you created it manually using retroarch.
